# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  profile: "chill"
  path_filters:
    - "scripts/**"
    - "frontend/**"
    - "src/**"
    - "tests/**"
